apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiren-config
spec:
  template:
    spec:
      containers:
      - name: jiren-config
        resources:
          requests:
            memory: 400Mi
            cpu: 100m
